
// This file was generated by Prisma, then adjusted to load `.env.local`
// (the project's convention for real env values; see CLAUDE.md).
import { config } from "dotenv";
import { defineConfig, env } from "prisma/config";

config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Demo courts + their hourly schedules. Idempotent — see prisma/seed.mts.
    seed: "tsx prisma/seed.mts",
  },
  engine: "classic",
  datasource: {
    // Migration/introspection connection. MUST be the DIRECT (session-mode)
    // connection, not the transaction pooler — migrations need session-level
    // features the transaction pooler (port 6543) does not support. Runtime
    // still uses DATABASE_URL (pooled) via the schema's datasource `url`.
    url: env("DIRECT_URL"),
  },
});
